#!/bin/bash

alias l='ls -lh'
alias ll='ls -lah'

alias rep='cd ~/Repositories'
alias dsk='cd ~/Desktop'
alias dwn='cd ~/Downloads'
alias tt='tmux ls 2>/dev/null || echo "no running sessions"'
alias ts='tmux new -s'
alias ta='tmux attach-session -t'
alias tree='tree -C'