#!/bin/bash

alias ls='ls --group-directories-first --color=auto'
alias l='ls -lh --group-directories-first --color=auto'
alias ll='ls -lah --group-directories-first --color=auto'

alias rep='cd ~/Repositories'
alias dsk='cd ~/Desktop'
alias dwn='cd ~/Downloads'

alias tt='tmux ls 2>/dev/null || echo "no running sessions"'
alias ts='tmux new -s'
alias ta='tmux attach-session -t'

alias tree='tree -C'
alias cat='batcat'